# Generated by Django 4.0.4 on 2022-06-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='front_cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
