# Generated by Django 4.0.4 on 2022-06-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('POR', 'Portuguese'), ('ENG', 'English')], default='PT', max_length=3, null=True),
        ),
    ]
