# Generated by Django 4.0.4 on 2022-06-17 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='back_cover',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='book',
            name='front_cover',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], name='books_book_title_4906cc_idx'),
        ),
    ]
