# Generated by Django 4.0.5 on 2022-06-29 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_back_cover_alter_book_front_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Action and adventure', 'Action and adventure'), ('Alternate history', 'Alternate history'), ('Anthology', 'Anthology'), ('Art and architecture', 'Art and architecture'), ('Autobiography', 'Autobiography'), ('Biography', 'Biography'), ('Business and economics', 'Business and economics'), ('Chick lit', 'Chick lit'), ("Children's", "Children's"), ('Classic', 'Classic'), ('Comic book', 'Comic book'), ('Cookbook', 'Cookbook'), ('Crafts and hobbies', 'Crafts and hobbies'), ('Diary', 'Diary'), ('Dictionary', 'Dictionary'), ('Drama', 'Drama'), ('Encyclopedia', 'Encyclopedia'), ('Fairytale', 'Fairytale'), ('Fantasy', 'Fantasy'), ('Graphic novel', 'Graphic novel'), ('Guide', 'Guide'), ('Health and fitness', 'Health and fitness'), ('Historical fiction', 'Historical fiction'), ('History', 'History'), ('Home and garden', 'Home and garden'), ('Horror', 'Horror'), ('Humor', 'Humor'), ('Journal', 'Journal'), ('Math', 'Math'), ('Memoir', 'Memoir'), ('Mystery', 'Mystery'), ('Paranormal romance', 'Paranormal romance'), ('Philosophy', 'Philosophy'), ('Picture book', 'Picture book'), ('Poetry', 'Poetry'), ('Political thriller', 'Political thriller'), ('Prayer', 'Prayer'), ('Religion and spirituality', 'Religion and spirituality'), ('Review', 'Review'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Science', 'Science'), ('Science fiction', 'Science fiction'), ('Self help', 'Self help'), ('Short story', 'Short story'), ('Sports and leisure', 'Sports and leisure'), ('Textbook', 'Textbook'), ('Thriller', 'Thriller'), ('Travel', 'Travel'), ('True crime', 'True crime'), ('Undefined', 'Undefined'), ('Western', 'Western')], default='Undefined', max_length=25),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='books.book'),
        ),
    ]
